# Generated by Django 5.2 on 2025-05-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('resolved', 'Résolu')], default='pending', max_length=50, verbose_name='Statut de la réclamation'),
        ),
    ]
